### ISSUE TITLE
Need Help for Note 12 Turbo

### ISSUE THREAD

**Issue by Tigercat000** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#103]
Refactoring parameters...
Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\PC\Desktop\PHP\bypass.php:229
Stack trace:
#0 C:\Users\PC\Desktop\PHP\bypass.php(329): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\PC\Desktop\PHP\bypass.php on line 229

**Comment by xbn2002** [comment]
Look #91 pls

**Comment by spiderfix101** [comment]
> Refactoring parameters... Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\PC\Desktop\PHP\bypass.php:229 Stack trace: #0 C:\Users\PC\Desktop\PHP\bypass.php(329): decryptData('8/8Mnp7WcRph8sb...') #1 {main} thrown in C:\Users\PC\Desktop\PHP\bypass.php on line 229

Hi, were you able to unlock the bootloader for Note 12 Turbo ? If yes, can you please tell me how did you do it. Thank you

**Comment by shenkunlovecoding** [comment]
Try using the Python version
