### ISSUE TITLE
error when trying to use on ubuntu

### ISSUE THREAD

**Issue by pulpoff** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#129]
[2024-06-03] [12:37:38] [INFO] - ************************************
[2024-06-03] [12:37:38] [INFO] - * Xiaomi HyperOS BootLoader Bypass *
[2024-06-03] [12:37:38] [INFO] - * By NekoYuzu          Version 1.0 *
[2024-06-03] [12:37:38] [INFO] - ************************************
[2024-06-03] [12:37:38] [INFO] - GitHub: https://github.com/MlgmXyysd
[2024-06-03] [12:37:38] [INFO] - XDA: https://xdaforums.com/m/mlgmxyysd.8430637
[2024-06-03] [12:37:38] [INFO] - X (Twitter): https://x.com/realMlgmXyysd
[2024-06-03] [12:37:38] [INFO] - PayPal: https://paypal.me/MlgmXyysd
[2024-06-03] [12:37:38] [INFO] - My Blog: https://www.neko.ink/
[2024-06-03] [12:37:38] [INFO] - ************************************
[2024-06-03] [12:37:38] [INFO] - Starting ADB server...
[2024-06-03] [12:37:38] [INFO] - Processing device 12fe97cc(device:lisa)...
[2024-06-03] [12:37:38] [INFO] - Finding BootLoader unlock bind request...
[2024-06-03] [12:37:39] [INFO] * Now you can bind account in the developer options.
adb: invalid transport id
[2024-06-03] [12:37:39] [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in /home/pulp/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 331 and defined in /home/pulp/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php:228
Stack trace:
#0 /home/pulp/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php(331): decryptData()
#1 {main}
  thrown in /home/pulp/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 228

**Comment by xy5a** [comment]
Same issue on Arch linux
```sh
❯ uname -a
Linux Thinkpad-E480 6.9.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000 x86_64 GNU/Linux
❯ php --version
PHP 8.3.8 (cli) (built: Jun  7 2024 19:46:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
❯ php bypass.php
[2024-06-13] [09:03:10] [INFO] - ************************************
[2024-06-13] [09:03:10] [INFO] - * Xiaomi HyperOS BootLoader Bypass *
[2024-06-13] [09:03:10] [INFO] - * By NekoYuzu          Version 1.0 *
[2024-06-13] [09:03:10] [INFO] - ************************************
[2024-06-13] [09:03:10] [INFO] - GitHub: https://github.com/MlgmXyysd
[2024-06-13] [09:03:10] [INFO] - XDA: https://xdaforums.com/m/mlgmxyysd.8430637
[2024-06-13] [09:03:10] [INFO] - X (Twitter): https://x.com/realMlgmXyysd
[2024-06-13] [09:03:10] [INFO] - PayPal: https://paypal.me/MlgmXyysd
[2024-06-13] [09:03:10] [INFO] - My Blog: https://www.neko.ink/
[2024-06-13] [09:03:10] [INFO] - ************************************
[2024-06-13] [09:03:10] [INFO] - Starting ADB server...
[2024-06-13] [09:03:10] [INFO] - Processing device ac3f0b75(device:pipa)...
[2024-06-13] [09:03:10] [INFO] - Finding BootLoader unlock bind request...
[2024-06-13] [09:03:10] [INFO] * Now you can bind account in the developer options.
adb: invalid transport id
[2024-06-13] [09:03:10] [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in /home/xy_5a/Sources/Xiaomi-HyperOS-BootLoader-Bypass/bypass.php on line 330 and defined in /home/xy_5a/Sources/Xiaomi-HyperOS-BootLoader-Bypass/bypass.php:228
Stack trace:
#0 /home/xy_5a/Sources/Xiaomi-HyperOS-BootLoader-Bypass/bypass.php(330): decryptData()
#1 {main}
  thrown in /home/xy_5a/Sources/Xiaomi-HyperOS-BootLoader-Bypass/bypass.php on line 228
```
