### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt()

### ISSUE THREAD

**Issue by JoSoG89** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#170]
This happen when click on add account

```
Refactoring parameters...
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\php-8\bypass.php:230
Stack trace:
#0 C:\php-8\bypass.php(330): decryptData('#&^grUo2DV4B8Nn...')
#1 {main}
  thrown in C:\php-8\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\php-8\bypass.php:230
Stack trace:
#0 C:\php-8\bypass.php(330): decryptData('#&^grUo2DV4B8Nn...')
#1 {main}
  thrown in C:\php-8\bypass.php on line 230``
```

**Comment by Dimitrysaf** [comment]
How did you fixed it?
