### ISSUE TITLE
fatal error?

### ISSUE THREAD

**Issue by Radiantguled** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#221]
![Screenshot (6)](https://github.com/user-attachments/assets/908cd558-0dc6-49c6-b330-d7635fc8c2eb)
i keep getting this error. i put the file in the c drive and ran it as administrator. Was their a new update to the hyper os?

**Comment by Madin-David** [comment]
This is caused by curl and openssl not being loaded
As you can see from the first few wanrning
The solution is to remove the ; before ;extension_dir=“ext” (line 768) in php.ini

**Comment by ginolaginola** [comment]
> This is caused by curl and openssl not being loaded As you can see from the first few wanrning The solution is to remove the ; before ;extension_dir=“ext” (line 768) in php.ini

I delete the ;extension_dir=“ext” , but the same problem.
When I want to add Mi accont in the developer option the mobile interenet closed, why? 

PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Miklos Tibor\Downloads\27\bypass.php:230
Stack trace:
#0 C:\Users\Miklos Tibor\Downloads\27\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\Miklos Tibor\Downloads\27\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Miklos Tibor\Downloads\27\bypass.php:230
Stack trace:
#0 C:\Users\Miklos Tibor\Downloads\27\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\Miklos Tibor\Downloads\27\bypass.php on line 230

**Comment by shenkunlovecoding** [comment]
Try using the Python version https://pan.baidu.com/s/1h-ok3CH3mFyMg4NxcWm3og?pwd=arap

**Comment by ginolaginola** [comment]
> Try using the Python version https://pan.baidu.com/s/1h-ok3CH3mFyMg4NxcWm3og?pwd=arap

Hi. Thanks.
What is this exe file?

**Comment by shenkunlovecoding** [comment]
The Python rewrite version of this repository, with the source code stored in my repository

**Comment by Zxingtsai** [comment]
Similar on MacOS
[2025-01-25] [15:31:55] [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 330 and defined in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php:228
Stack trace:
#0 /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php(330): decryptData(NULL)
#1 {main}
  thrown in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 228

Fatal error: Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 330 and defined in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php:228
Stack trace:
#0 /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php(330): decryptData(NULL)
#1 {main}
  thrown in /Users/jiangyunqin/Downloads/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 228

**Comment by Madin-David** [comment]
> > This is caused by curl and openssl not being loaded As you can see from the first few wanrning The solution is to remove the ; before ;extension_dir=“ext” (line 768) in php.ini
> 
> I delete the ;extension_dir=“ext” , but the same problem. When I want to add Mi accont in the developer option the mobile interenet closed, why?
> 
> PHP Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Miklos Tibor\Downloads\27\bypass.php:230 Stack trace: #0 C:\Users\Miklos Tibor\Downloads\27\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...') [#1](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/1) {main} thrown in C:\Users\Miklos Tibor\Downloads\27\bypass.php on line 230
> 
> Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Miklos Tibor\Downloads\27\bypass.php:230 Stack trace: #0 C:\Users\Miklos Tibor\Downloads\27\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...') [#1](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/1) {main} thrown in C:\Users\Miklos Tibor\Downloads\27\bypass.php on line 230

Try not delete  ;extension_dir=“ext”
delete the ; before  ;extension_dir=“ext”
that is to say to change  ;extension_dir=“ext” into  extension_dir=“ext”

**Comment by BroddyDumpcode** [comment]
solved, cuz I removed the ";" in ;extension_dir = "ext"
