### ISSUE TITLE
Problems which is not normal to experience

### ISSUE THREAD

**Issue by CeeVeiKey** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#227]
i have no idea what to do next 
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in D:\Files\Programs\Tool\Hyper OS\php\bypass.php:230
Stack trace:
#0 D:\Files\Programs\Tool\Hyper OS\php\bypass.php(330): decryptData('#&^Gvzi+xHd0h4c...')
#1 {main}
  thrown in D:\Files\Programs\Tool\Hyper OS\php\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in D:\Files\Programs\Tool\Hyper OS\php\bypass.php:230
Stack trace:
#0 D:\Files\Programs\Tool\Hyper OS\php\bypass.php(330): decryptData('#&^Gvzi+xHd0h4c...')
#1 {main}
  thrown in D:\Files\Programs\Tool\Hyper OS\php\bypass.php on line 230
  
<img width="672" alt="image" src="https://github.com/user-attachments/assets/ed25b2ef-a137-4426-8e36-635c288eca57" />

**Comment by CeeVeiKey** [comment]
@MlgmXyysd please help me in case you are free, people in my local area always take charge of this kind of service. 
Which is very inconvenient for me due to fact that I'm a student.

**Comment by ginolaginola** [comment]
I have the same error, can you unlock?

**Comment by CeeVeiKey** [comment]
Can't, things seem to be overloaded daily

Vào 19:30 Th 6, 27 thg 12, 2024 ginolaginola ***@***.***> đã
viết:

**Comment by mdan96** [comment]
Hi, you can fix this by opening php.ini and change 
` ;extension_dir = "ext" into extension_dir = "ext"  ( remove **;** ) `

**Comment by CeeVeiKey** [comment]
Thanks, I'll check it out.

Vào 23:46 Th 7, 11 thg 1, 2025 mdan96 ***@***.***> đã viết:

**Comment by CeeVeiKey** [comment]
[image: image.png]I'm having this problem. Could you please help me any
further?

Vào Th 7, 11 thg 1, 2025 vào lúc 23:46 mdan96 ***@***.***>
đã viết:
