### ISSUE TITLE
cmd报错,k70u 1.0.22.0

### ISSUE THREAD

**Issue by yiquandi** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#230]
尝试绑定设备后出现的提示
 - Account bind request found! Let's block it.
[2024-12-15] [15:38:43] [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\澎湃oS解锁\bypass.php:229
Stack trace:
#0 C:\澎湃oS解锁\bypass.php(329): decryptData('#&^MoYQlpKOrULt...')
#1 {main}
  thrown in C:\澎湃oS解锁\bypass.php on line 229

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\澎湃oS解锁\bypass.php:229
Stack trace:
#0 C:\澎湃oS解锁\bypass.php(329): decryptData('#&^MoYQlpKOrULt...')
#1 {main}
  thrown in C:\澎湃oS解锁\bypass.php on line 229

**Comment by 0xSelenicDove** [comment]
用[这个](https://github.com/TheAirBlow/HyperSploit)。这是个单一exe文件，所以不会有php错误。
